compile:
  libraries:
    - BresserWeatherSensorReceiver
    - MCCI Arduino LoRaWAN Library
    - MCCI LoRaWAN LMIC library
    - MCCI Arduino Development Kit ADK
    - LoRa Serialization
    - ESP32Time
    - ESP32AnalogRead
    - OneWireNg
    - DallasTemperature
    - ATC_MiThermometer
    - TheengsDecoder
  platforms:
    - esp32

unittest:
  libraries:
    - BresserWeatherSensorReceiver
    - MCCI Arduino LoRaWAN Library
    - MCCI LoRaWAN LMIC library
    - MCCI Arduino Development Kit ADK
    - LoRa Serialization
    - ESP32Time
    - ESP32AnalogRead
    - OneWireNg
    - DallasTemperature
    - ATC_MiThermometer
    - TheengsDecoder
  platforms:
    - esp32
